#theme: jekyll-theme-cayman
remote_theme: Sylhare/Type-on-Strap
markdown: kramdown
github: [metadata]
encoding: UTF-8
kramdown:
input: GFM
hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
title: 1 pas, 2 côtés
avatar: emmanuel_400x400.jpg
